agent = []

[workspace]
prefix = "hq"
provider = "claude"

[[rigs]]
name = "enterprise"
prefix = "sc"
dolt_host = "127.0.0.1"
dolt_port = "58414"

[[rigs.overrides]]
agent = "polecat"
[rigs.overrides.env]
GC_TARGET_BRANCH = "boylec/develop"

[[rigs.overrides]]
agent = "polecat-sonnet"
[rigs.overrides.env]
GC_TARGET_BRANCH = "boylec/develop"

[[rigs.overrides]]
agent = "polecat-opus-high"
[rigs.overrides.env]
GC_TARGET_BRANCH = "boylec/develop"

[[rigs.overrides]]
agent = "polecat-opus-max-1m"
[rigs.overrides.env]
GC_TARGET_BRANCH = "boylec/develop"

[[rigs.overrides]]
agent = "refinery"
[rigs.overrides.env]
GC_TARGET_BRANCH = "boylec/develop"

[[rigs]]
name = "gascity"
prefix = "gc"
dolt_host = "127.0.0.1"
dolt_port = "58415"

[[rigs]]
name = "designsystem"
prefix = "de"
suspended = true
dolt_host = "127.0.0.1"
dolt_port = "53930"

[session]
startup_timeout = "180s"

[daemon]
patrol_interval = "30s"
max_restarts = 5
restart_window = "1h"
shutdown_timeout = "5s"
